[global]
    workgroup = WORKGROUP
    server role = standalone server
    security = user
    map to guest = never
    restrict anonymous = 2
    usershare allow guests = no
    disable netbios = yes
    smb ports = 445
    server min protocol = SMB2

    passdb backend = tdbsam
    obey pam restrictions = no
    unix password sync = no
    pam password change = no

    load printers = no
    printing = bsd
    printcap name = /dev/null
    disable spoolss = yes

    logging = file
    log level = 1
    log file = /logs/samba_raw.log
    max log size = 0

    access based share enum = yes

[ebooks]
    path = /libraryit/ebooks
    browseable = yes
    guest ok = no
    read only = no
    valid users = @staff @readonly
    write list = @staff
    read list = @readonly
    create mask = 0664
    directory mask = 0775
    force group = staff
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = all
    full_audit:failure = all
    full_audit:syslog = false

[papers]
    path = /libraryit/papers
    browseable = yes
    guest ok = no
    read only = no
    valid users = @staff @readonly
    write list = @staff
    read list = @readonly
    create mask = 0664
    directory mask = 0775
    force group = staff
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = all
    full_audit:failure = all
    full_audit:syslog = false

[sourcecode]
    path = /libraryit/sourcecode
    browseable = yes
    guest ok = no
    read only = yes
    valid users = @staff
    invalid users = @readonly
    hide unreadable = yes
    create mask = 0640
    directory mask = 0750
    force group = staff
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = all
    full_audit:failure = all
    full_audit:syslog = false

[docs]
    path = /libraryit/docs
    browseable = yes
    guest ok = no
    read only = yes
    valid users = @staff @readonly
    read list = contributor @readonly
    write list = librarian
    create mask = 0664
    directory mask = 0775
    force group = staff
    vfs objects = full_audit
    full_audit:prefix = %u|%S
    full_audit:success = all
    full_audit:failure = all
    full_audit:syslog = false
